dependencies:
  - python=3.8
  - sphinx_rtd_theme
  - jinja2
  - tornado
  - nbformat
  - jupyter_client
  - ipykernel
  - pip
  - sphinx
  - terminado
  - myst-parser
  - pip:
    - nbsphinx
    - Send2Trash
    - prometheus_client
    - sphinxcontrib_github_alt
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - tqdm
    - sklearn
    - Pillow
    - xgboost
    - sympy
    - requests
    - lightgbm
    - catboost
